version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: gg
      POSTGRES_USER: gg
      POSTGRES_PASSWORD: 123123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: